title: The Codedhans
email: codedspace1@gmail.com
description: Art of Software.
baseurl: "" 
url: "https://codedhans.github.io"

# Build settings
remote_theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# This is the most important part to prevent the "Build with Jekyll" crash
future: true
incremental: false
